name: Deploy Backend Docker Image

on:
  push:
    branches: [ production ]
    paths:
      - 'server/**'
      - '.github/workflows/deploy-backend.yml'
  create:

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/convocationmedal-backend

jobs:
  build-and-deploy:
    name: Build Backend (${{ github.ref == 'refs/heads/production' && 'Production' || 'Development' }})
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'create' && github.ref == 'refs/heads/production')
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=latest

    - name: Display build information
      run: |
        echo "Building backend image..."
        echo "Registry: ${{ env.REGISTRY }}"
        echo "Image: ${{ env.IMAGE_NAME }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Event: ${{ github.event_name }}"
        echo "Push to registry: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./server
        file: ./server/Dockerfile
        push: ${{ github.ref == 'refs/heads/production' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
